apiVersion: v1
kind: Service
metadata:
  name: spam-detector
  labels:
    app: spam-detector
spec:
  type: NodePort
  selector:
    app: spam-detector
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080
    protocol: TCP
    name: http
